[package]
name = "Abdal_HTTP_HEAD_Flood"
version = "0.1.10"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json", "gzip", "stream", "cookies", "blocking", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
colored = "2.0"